Run e2e-tests against the built image

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -72,3 +72,45 @@ jobs:
         with:
           name: elixir_script
           path: /tmp/elixir_script.tar
+
+  e2e-tests:
+    needs: [ build ]
+    strategy:
+      fail-fast: false
+      matrix:
+        data:
+          - name: "return"
+            script: |
+              "return"
+            expected: "return"
+
+          - name: "context"
+            script: |
+              Map.keys(context)
+            expected: "[__struct__,action,actor,api_url,event_name,graphql_url,job,payload,ref,run_id,run_number,server_url,sha,workflow]"
+    runs-on: ubuntu-latest
+    name: "e2e tests (${{ matrix.data.name }})"
+    steps:
+      - uses: actions/checkout@v3
+      - name: Download artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: elixir_script
+          path: /tmp
+      - name: Load image
+        run: docker load --input /tmp/elixir_script.tar
+      - name: Update action.yml to point to elixir_script:test
+        run: |
+          sed -i 's/\(  image: \).*/\1elixir_script:test/' action.yml
+      - name: Run gaggle/elixir_script
+        id: run
+        uses: ./
+        with:
+          script: |
+            ${{ matrix.data.script }}
+      - name: Assert output
+        run: |
+          expected="${{ matrix.data.expected }}"
+          output="${{steps.run.outputs.result}}"
+          [[ "$output" != "$expected" ]] && echo "::error::❌ Expected '$expected', got '$output'" && exit 1
+          echo "✅ Test passed, outputs.result: ${{toJSON(steps.run.outputs.result)}}"
